INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (1, 'George Spence', 'Great textbook.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (2, 'Jose Alvarez', 'Amazing reference.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (3, 'Michael Nolan', 'Good textbook.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (4, 'Alex Johnson', 'This book could be better.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (5, 'Jordan Smith', 'This book is terrible','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (1, 'Calculus: A Modeling Approach', 'Marvin L. Bittinger', 'Addison-Wesley', 'License I','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (2, 'Chemistry: The Molecular Nature of Matter and Change', 'Martin Silderberg', 'McGraw-Hill', 'License II','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (3, 'Psychology: Themes and Variations', 'Wayne Weiten', 'Wadsworth Publishing', 'License III', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (4, 'Economics: A Contemporary Introduction', 'William A. McEachern', 'South-Western Pub', 'License IV', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (5, 'Physics: Principles With Applications', 'Douglas C. Giancoli', 'Prentice Hall', 'License V', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

alter sequence hibernate_sequence restart with 25;