-- INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (1, 'George Spence', 'Great textbook.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (2, 'Jose Alvarez', 'Amazing reference.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (3, 'Michael Nolan', 'Good textbook.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (4, 'Alex Johnson', 'This book could be better.','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO review (reviewid, reviewer, review, created_by, created_date, last_modified_by, last_modified_date) VALUES (5, 'Jordan Smith', 'This book is terrible','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (1, 'Calculus: A Modeling Approach', 'Marvin L. Bittinger, David J. Ellenbogen', 'Addison-Wesley', 'License I','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (2, 'Chemistry: The Molecular Nature of Matter and Change', 'Martin Silderberg', 'McGraw-Hill', 'License II','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (3, 'Psychology: Themes and Variations', 'Wayne Weiten', 'Wadsworth Publishing', 'License III', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (4, 'Economics: A Contemporary Introduction', 'William A. McEachern', 'South-Western Pub', 'License IV', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (5, 'Physics: Principles With Applications', 'Douglas C. Giancoli', 'Prentice Hall', 'License V', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (6, 'Macroeconomics', 'Roger A. Arnold', 'South-Western College Publ.', 'License I','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (7, 'Precalculus', 'Margaret L. Lial', 'Scott, Foresman', 'License II','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (8, 'Electromagnetism, 2E', 'I. S. Grant, W. R. Phillips', 'Wiley', 'License III', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (9, 'Engineering', 'George C. Beakley', 'Macmillan Pub. Co., Collier Macmillan Publishers', 'License IV', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (10, 'Linear Algebra', 'John B. Fraleigh, Raymond A. Beauregard', 'Addison-Wesley', 'License V', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (11, 'The American Pageant', 'David M. Kennedy', 'Houghton Mifflin', 'License I','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (12, 'Thermodynamics', 'Kenneth Wark, Don Richards', 'WCB McGraw-Hill', 'License II','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (13, 'Microeconomics', 'David Besanko, Ronald R. Braeutigam', 'Wiley', 'License III', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (14, 'Calculus', 'Earl William Swokowski', 'PWS Pub. Co.', 'License IV', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
-- INSERT INTO book (bookid, title, author, publisher, license, created_by, created_date, last_modified_by, last_modified_date) VALUES (15, 'Applied Calculus', 'Stefan Waner', 'Thomson-Brooks/Cole', 'License V', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

alter sequence hibernate_sequence restart with 25;